# Generated by Django 3.2.8 on 2021-11-07 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=20)),
                ('part_number', models.IntegerField(default=0)),
                ('part_type', models.CharField(max_length=50)),
                ('part_manufacture_date', models.DateField(verbose_name='date part was manufactured')),
            ],
        ),
        migrations.CreateModel(
            name='VW_Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=20)),
                ('car_colour', models.CharField(max_length=20)),
                ('car_number_of_doors', models.IntegerField(default=0)),
                ('car_manufacture_date', models.DateField(verbose_name='date car was manufactured')),
                ('car_transmission', models.CharField(max_length=20)),
                ('car_price', models.IntegerField(default=0)),
                ('parts', models.ManyToManyField(blank=True, related_name='car_parts', to='app1.Part')),
            ],
        ),
    ]
